.section .literal, "ax"
.align 4

.L_PIN_FUNC_GPIO: .word (1 << 12) | (2 << 8)

.L_GPIO1_MUX:       .word
.L_GPIO1_ENABLE:    .word
.L_GPIO1_W1TS:      .word
.L_GPIO1_W1TC:      .word
.L_GPIO1_MASK:      .word

.L_GPIO2_MUX:       .word
.L_GPIO2_ENABLE:    .word
.L_GPIO2_W1TS:      .word
.L_GPIO2_W1TC:      .word
.L_GPIO2_MASK:      .word

.L_GPIO3_MUX:       .word
.L_GPIO3_ENABLE:    .word
.L_GPIO3_W1TS:      .word
.L_GPIO3_W1TC:      .word
.L_GPIO3_MASK:      .word

.L_GPIO4_MUX:       .word
.L_GPIO4_ENABLE:    .word
.L_GPIO4_W1TS:      .word
.L_GPIO4_W1TC:      .word
.L_GPIO4_MASK:      .word

.L_GPIO5_MUX:       .word
.L_GPIO5_ENABLE:    .word
.L_GPIO5_W1TS:      .word
.L_GPIO5_W1TC:      .word
.L_GPIO5_MASK:      .word

.L_GPIO6_MUX:       .word
.L_GPIO6_ENABLE:    .word
.L_GPIO6_W1TS:      .word
.L_GPIO6_W1TC:      .word
.L_GPIO6_MASK:      .word

.L_GPIO7_MUX:       .word
.L_GPIO7_ENABLE:    .word
.L_GPIO7_W1TS:      .word
.L_GPIO7_W1TC:      .word
.L_GPIO7_MASK:      .word

.L_GPIO8_MUX:       .word
.L_GPIO8_ENABLE:    .word
.L_GPIO8_W1TS:      .word
.L_GPIO8_W1TC:      .word
.L_GPIO8_MASK:      .word

.L_GPIO9_MUX:       .word
.L_GPIO9_ENABLE:    .word
.L_GPIO9_W1TS:      .word
.L_GPIO9_W1TC:      .word
.L_GPIO9_MASK:      .word

.L_GPIO10_MUX:       .word
.L_GPIO10_ENABLE:    .word
.L_GPIO10_W1TS:      .word
.L_GPIO10_W1TC:      .word
.L_GPIO10_MASK:      .word

.L_GPIO11_MUX:       .word
.L_GPIO11_ENABLE:    .word
.L_GPIO11_W1TS:      .word
.L_GPIO11_W1TC:      .word
.L_GPIO11_MASK:      .word

.L_GPIO12_MUX:       .word
.L_GPIO12_ENABLE:    .word
.L_GPIO12_W1TS:      .word
.L_GPIO12_W1TC:      .word
.L_GPIO12_MASK:      .word

.L_GPIO13_MUX:       .word
.L_GPIO13_ENABLE:    .word
.L_GPIO13_W1TS:      .word
.L_GPIO13_W1TC:      .word
.L_GPIO13_MASK:      .word

.L_GPIO14_MUX:       .word
.L_GPIO14_ENABLE:    .word
.L_GPIO14_W1TS:      .word
.L_GPIO14_W1TC:      .word
.L_GPIO14_MASK:      .word

.L_GPIO15_MUX:       .word
.L_GPIO15_ENABLE:    .word
.L_GPIO15_W1TS:      .word
.L_GPIO15_W1TC:      .word
.L_GPIO15_MASK:      .word

.L_GPIO16_MUX:       .word
.L_GPIO16_ENABLE:    .word
.L_GPIO16_W1TS:      .word
.L_GPIO16_W1TC:      .word
.L_GPIO16_MASK:      .word

.L_GPIO17_MUX:       .word
.L_GPIO17_ENABLE:    .word
.L_GPIO17_W1TS:      .word
.L_GPIO17_W1TC:      .word
.L_GPIO17_MASK:      .word

.L_GPIO18_MUX:       .word
.L_GPIO18_ENABLE:    .word
.L_GPIO18_W1TS:      .word
.L_GPIO18_W1TC:      .word
.L_GPIO18_MASK:      .word

.L_GPIO19_MUX:       .word
.L_GPIO19_ENABLE:    .word
.L_GPIO19_W1TS:      .word
.L_GPIO19_W1TC:      .word
.L_GPIO19_MASK:      .word

.L_GPIO20_MUX:       .word
.L_GPIO20_ENABLE:    .word
.L_GPIO20_W1TS:      .word
.L_GPIO20_W1TC:      .word
.L_GPIO20_MASK:      .word

.L_GPIO21_MUX:       .word
.L_GPIO21_ENABLE:    .word
.L_GPIO21_W1TS:      .word
.L_GPIO21_W1TC:      .word
.L_GPIO21_MASK:      .word

.L_GPIO22_MUX:       .word
.L_GPIO22_ENABLE:    .word
.L_GPIO22_W1TS:      .word
.L_GPIO22_W1TC:      .word
.L_GPIO22_MASK:      .word

.L_GPIO23_MUX:       .word
.L_GPIO23_ENABLE:    .word
.L_GPIO23_W1TS:      .word
.L_GPIO23_W1TC:      .word
.L_GPIO23_MASK:      .word

.L_GPIO24_MUX:       .word
.L_GPIO24_ENABLE:    .word
.L_GPIO24_W1TS:      .word
.L_GPIO24_W1TC:      .word
.L_GPIO24_MASK:      .word

.L_GPIO25_MUX:       .word
.L_GPIO25_ENABLE:    .word
.L_GPIO25_W1TS:      .word
.L_GPIO25_W1TC:      .word
.L_GPIO25_MASK:      .word

.L_GPIO26_MUX:       .word
.L_GPIO26_ENABLE:    .word
.L_GPIO26_W1TS:      .word
.L_GPIO26_W1TC:      .word
.L_GPIO26_MASK:      .word

.L_GPIO27_MUX:       .word
.L_GPIO27_ENABLE:    .word
.L_GPIO27_W1TS:      .word
.L_GPIO27_W1TC:      .word
.L_GPIO27_MASK:      .word

.L_GPIO28_MUX:       .word
.L_GPIO28_ENABLE:    .word
.L_GPIO28_W1TS:      .word
.L_GPIO28_W1TC:      .word
.L_GPIO28_MASK:      .word

.L_GPIO29_MUX:       .word
.L_GPIO29_ENABLE:    .word
.L_GPIO29_W1TS:      .word
.L_GPIO29_W1TC:      .word
.L_GPIO29_MASK:      .word

.L_GPIO30_MUX:       .word
.L_GPIO30_ENABLE:    .word
.L_GPIO30_W1TS:      .word
.L_GPIO30_W1TC:      .word
.L_GPIO30_MASK:      .word

.L_GPIO31_MUX:       .word
.L_GPIO31_ENABLE:    .word
.L_GPIO31_W1TS:      .word
.L_GPIO31_W1TC:      .word
.L_GPIO31_MASK:      .word

.L_GPIO32_MUX:       .word
.L_GPIO32_ENABLE:    .word
.L_GPIO32_W1TS:      .word
.L_GPIO32_W1TC:      .word
.L_GPIO32_MASK:      .word

.L_GPIO33_MUX:       .word
.L_GPIO33_ENABLE:    .word
.L_GPIO33_W1TS:      .word
.L_GPIO33_W1TC:      .word
.L_GPIO33_MASK:      .word

.L_GPIO34_MUX:       .word
.L_GPIO34_ENABLE:    .word
.L_GPIO34_W1TS:      .word
.L_GPIO34_W1TC:      .word
.L_GPIO34_MASK:      .word

.L_GPIO35_MUX:       .word
.L_GPIO35_ENABLE:    .word
.L_GPIO35_W1TS:      .word
.L_GPIO35_W1TC:      .word
.L_GPIO35_MASK:      .word

.L_GPIO36_MUX:       .word
.L_GPIO36_ENABLE:    .word
.L_GPIO36_W1TS:      .word
.L_GPIO36_W1TC:      .word
.L_GPIO36_MASK:      .word

.L_GPIO37_MUX:       .word
.L_GPIO37_ENABLE:    .word
.L_GPIO37_W1TS:      .word
.L_GPIO37_W1TC:      .word
.L_GPIO37_MASK:      .word

.L_GPIO38_MUX:       .word
.L_GPIO38_ENABLE:    .word
.L_GPIO38_W1TS:      .word
.L_GPIO38_W1TC:      .word
.L_GPIO38_MASK:      .word

.L_GPIO39_MUX:       .word
.L_GPIO39_ENABLE:    .word
.L_GPIO39_W1TS:      .word
.L_GPIO39_W1TC:      .word
.L_GPIO39_MASK:      .word

.L_GPIO40_MUX:       .word
.L_GPIO40_ENABLE:    .word
.L_GPIO40_W1TS:      .word
.L_GPIO40_W1TC:      .word
.L_GPIO40_MASK:      .word

.L_GPIO41_MUX:       .word
.L_GPIO41_ENABLE:    .word
.L_GPIO41_W1TS:      .word
.L_GPIO41_W1TC:      .word
.L_GPIO41_MASK:      .word

.L_GPIO42_MUX:       .word
.L_GPIO42_ENABLE:    .word
.L_GPIO42_W1TS:      .word
.L_GPIO42_W1TC:      .word
.L_GPIO42_MASK:      .word

.L_GPIO43_MUX:       .word
.L_GPIO43_ENABLE:    .word
.L_GPIO43_W1TS:      .word
.L_GPIO43_W1TC:      .word
.L_GPIO43_MASK:      .word

.L_GPIO44_MUX:       .word
.L_GPIO44_ENABLE:    .word
.L_GPIO44_W1TS:      .word
.L_GPIO44_W1TC:      .word
.L_GPIO44_MASK:      .word

.L_GPIO45_MUX:       .word
.L_GPIO45_ENABLE:    .word
.L_GPIO45_W1TS:      .word
.L_GPIO45_W1TC:      .word
.L_GPIO45_MASK:      .word

.L_GPIO46_MUX:       .word
.L_GPIO46_ENABLE:    .word
.L_GPIO46_W1TS:      .word
.L_GPIO46_W1TC:      .word
.L_GPIO46_MASK:      .word

.L_GPIO47_MUX:       .word
.L_GPIO47_ENABLE:    .word
.L_GPIO47_W1TS:      .word
.L_GPIO47_W1TC:      .word
.L_GPIO47_MASK:      .word

.L_GPIO48_MUX:       .word
.L_GPIO48_ENABLE:    .word
.L_GPIO48_W1TS:      .word
.L_GPIO48_W1TC:      .word
.L_GPIO48_MASK:      .word

.section .text.main
.global main
.type main, @function

main:
_kernelLoop:

    j _kernelLoop